sudo: required
services:
  - docker
before_install:
  - docker build -t javaapp1 .
script:
  - nohup docker run -e CI=true -p 8080:8080 javaapp1 &
before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAXGSUQVYHDRLG2GDW"
  secret_access_key:
    secure: "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"
  region: "us-east-2"
  app: "javaapp5"
  env: "Javaapp5-env"
  bucket_name: "elasticbeanstalk-us-east-2-495172234766"

after_deploy:
  - echo "done deployment..."