version: '3'
services:
        web:
                stdin_open: true
                build:
                        context: .
                ports:
                        - "8080:8080"
                volumes:
                        - ".:/usr/src/myapp"